[package]

name = "testp"
version = "0.0.1"
authors = ["Thomas Jespersen <laumann.thomas@gmail.com>"]

[dependencies]
serde_derive = "*"

[dev-dependencies.compiletest_rs]
path = ".."
features = ["tmp"]

[features]
stable = ["compiletest_rs/stable"]
